# Generated by Django 5.2 on 2025-06-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income_Category',
            new_name='Source',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income_category',
            new_name='source',
        ),
    ]
